"""Entry point for `python -m nflcarddb`.

Installing the package also puts an `nflcarddb.exe` on PATH, and that file is
generated by pip rather than shipped by anyone -- so it carries no signature.
A Windows machine running Device Guard refuses to start it:

    'venv\\Scripts\\nflcarddb.exe' was blocked by your organization's
    Device Guard policy.

Nothing is wrong with the program; the launcher is simply an unsigned binary
that appeared in a user folder. Running the module through the interpreter
sidesteps the whole question, because python.exe is signed by the people who
publish Python and a virtual environment copies that signature along with the
file. Every .bat in this project calls the module this way for that reason.
"""

from .cli import main

raise SystemExit(main())
