"""Export the local database into SQL that Cloudflare D1 can load.

Two things this deliberately does differently from the local schema:

* The sales/cards join is flattened. The API only reads, D1 bills by rows
  scanned, and joining on every request buys nothing that can be done once here.
* Best-offer prices become NULL rather than the asking price. eBay publishes the
  seller's ask on those, not what the buyer paid, so serving it as `price` would
  be publishing a wrong number. NULL cannot be averaged by accident.

API keys are generated here and only the SHA-256 hash is exported, so the
database never contains a working credential -- not even in the file that
creates it.
"""

from __future__ import annotations

import hashlib
import secrets
import sqlite3
import statistics
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Optional

from . import db as store

# D1 rejects very large statements, so rows go out in batches.
ROWS_PER_INSERT = 200

EXPORT_COLUMNS = (
    "item_id", "sold_date", "title", "price_cents", "shipping_cents", "currency",
    "best_offer", "listing_format", "bids", "image_url", "player", "team", "year",
    "brand", "set_name", "parallel", "card_number", "grader", "grade", "is_rookie",
    "is_auto", "confidence",
)


def new_api_key(prefix: str = "nfl") -> tuple[str, str]:
    """Return (key, sha256). The key is shown once and never stored."""
    key = f"{prefix}_{secrets.token_urlsafe(32)}"
    return (key, hashlib.sha256(key.encode()).hexdigest())


def _sql_literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def _rows_to_export(conn: sqlite3.Connection, since: Optional[str]) -> list[sqlite3.Row]:
    where = "WHERE s.sold_date IS NOT NULL"
    params: tuple = ()
    if since:
        where += " AND s.sold_date >= ?"
        params = (since,)

    return conn.execute(
        f"""
        SELECT s.item_id, s.sold_date, s.title,
               -- A best offer has no published sale price; do not pretend it does.
               CASE WHEN s.best_offer = 1 THEN NULL ELSE s.price_cents END AS price_cents,
               s.shipping_cents, s.currency, s.best_offer, s.listing_format, s.bids,
               s.image_url,
               c.player, c.team, c.year, c.brand, c.set_name, c.parallel,
               c.card_number, c.grader, c.grade, c.is_rookie, c.is_auto,
               COALESCE(c.confidence, 0) AS confidence
        FROM sales s LEFT JOIN cards c USING (item_id)
        {where}
        ORDER BY s.sold_date
        """,
        params,
    ).fetchall()


def _daily_rollups(conn: sqlite3.Connection, since: Optional[str]) -> list[dict]:
    where = "WHERE sold_date IS NOT NULL"
    params: tuple = ()
    if since:
        where += " AND sold_date >= ?"
        params = (since,)

    counts = {
        r[0]: r[1] for r in conn.execute(
            f"SELECT sold_date, COUNT(*) FROM sales {where} GROUP BY sold_date", params
        )
    }
    prices: dict[str, list[int]] = {}
    for day, cents in conn.execute(
        f"SELECT sold_date, price_cents FROM sales {where} "
        f"AND best_offer = 0 AND price_cents IS NOT NULL AND currency = 'USD'",
        params,
    ):
        prices.setdefault(day, []).append(cents)

    out = []
    for day in sorted(counts):
        vals = sorted(prices.get(day, []))
        median = int(statistics.median(vals)) if vals else None
        p90 = vals[min(len(vals) - 1, int(round((len(vals) - 1) * 0.9)))] if vals else None
        out.append({
            "sold_date": day,
            "sales": counts[day],
            "priced": len(vals),
            "median_cents": median,
            "p90_cents": p90,
            "total_cents": sum(vals) if vals else None,
        })
    return out


def build_sql(
    db_path: str | Path,
    since: Optional[str] = None,
    key_hashes: Optional[Iterable[tuple[str, str]]] = None,
) -> tuple[str, dict]:
    """Build the D1 import script. Returns (sql, stats)."""
    conn = store.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        rows = _rows_to_export(conn, since)
        rollups = _daily_rollups(conn, since)
    finally:
        conn.close()

    lines: list[str] = [
        "-- Generated by `nflcarddb export-api`. Safe to re-run:",
        "-- sales upsert on item_id, so a re-import updates rather than duplicates.",
    ]

    cols = ", ".join(EXPORT_COLUMNS)
    updates = ", ".join(
        f"{c} = excluded.{c}" for c in EXPORT_COLUMNS if c != "item_id"
    )
    for start in range(0, len(rows), ROWS_PER_INSERT):
        chunk = rows[start:start + ROWS_PER_INSERT]
        values = ",\n  ".join(
            "(" + ", ".join(_sql_literal(r[c]) for c in EXPORT_COLUMNS) + ")"
            for r in chunk
        )
        lines.append(
            f"INSERT INTO sales ({cols}) VALUES\n  {values}\n"
            f"ON CONFLICT(item_id) DO UPDATE SET {updates};"
        )

    for start in range(0, len(rollups), ROWS_PER_INSERT):
        chunk = rollups[start:start + ROWS_PER_INSERT]
        values = ",\n  ".join(
            "(" + ", ".join(_sql_literal(d[k]) for k in
                            ("sold_date", "sales", "priced", "median_cents",
                             "p90_cents", "total_cents")) + ")"
            for d in chunk
        )
        lines.append(
            "INSERT INTO daily (sold_date, sales, priced, median_cents, p90_cents, "
            f"total_cents) VALUES\n  {values}\n"
            "ON CONFLICT(sold_date) DO UPDATE SET sales = excluded.sales, "
            "priced = excluded.priced, median_cents = excluded.median_cents, "
            "p90_cents = excluded.p90_cents, total_cents = excluded.total_cents;"
        )

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    for key_hash, label in (key_hashes or []):
        lines.append(
            "INSERT INTO api_keys (key_hash, label, created_at) VALUES "
            f"({_sql_literal(key_hash)}, {_sql_literal(label)}, {_sql_literal(now)}) "
            "ON CONFLICT(key_hash) DO UPDATE SET revoked = 0;"
        )

    lines.append(
        f"INSERT INTO meta (k, v) VALUES ('updated_at', {_sql_literal(now)}) "
        "ON CONFLICT(k) DO UPDATE SET v = excluded.v;"
    )

    stats = {
        "rows": len(rows),
        "days": len(rollups),
        "since": since,
        "keys_added": len(list(key_hashes or [])),
        "generated_at": now,
    }
    return ("\n".join(lines) + "\n", stats)


def export_api_sql(
    db_path: str | Path,
    out_path: str | Path,
    since: Optional[str] = None,
    key_hashes: Optional[Iterable[tuple[str, str]]] = None,
) -> dict:
    sql, stats = build_sql(db_path, since, list(key_hashes or []))
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sql, encoding="utf-8")
    stats["file"] = str(out)
    stats["bytes"] = len(sql)
    return stats
